/**
 *@Generated by sagacity-quickvo 4.13
 */
package vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import vo.base.AbstractSysLocationVO;

import java.math.BigDecimal;

/**
 * @project chome
 * @author jobell
 * @version 1.0.0
 * Table: sys_location,Remark:地方表 	
 */
@SqlToyEntity
public class SysLocationVO extends AbstractSysLocationVO {
	/**
	 * 
	 */
	private static final long serialVersionUID = 593012368611152965L;
	
	/** default constructor */
	public SysLocationVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public SysLocationVO(Long locationId)
	{
		this.locationId=locationId;
	}


	/** full constructor */
	public SysLocationVO(Long locationId, String locationName, String locationInfo, BigDecimal longitude, BigDecimal latitude, Integer status, Long areaCode, Integer publicFlag, Integer virtualFlag, String groupChatId, Long locationType, String locationBackimg)
	{
		this.locationId=locationId;
		this.locationName=locationName;
		this.locationInfo=locationInfo;
		this.longitude=longitude;
		this.latitude=latitude;
		this.status=status;
		this.areaCode=areaCode;
		this.publicFlag=publicFlag;
		this.virtualFlag=virtualFlag;
		this.groupChatId=groupChatId;
		this.locationType=locationType;
		this.locationBackimg=locationBackimg;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public SysLocationVO clone() {
		try {
			return (SysLocationVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
